// <auto-generated />
using ManageAirliness.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManageAirliness.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220525124554_initialmigration2")]
    partial class initialmigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ManageAirliness.Model.Airlines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirlineAddress");

                    b.Property<int>("AirlineContactNumber");

                    b.Property<string>("AirlineName");

                    b.Property<double>("AirlinePrice");

                    b.Property<int>("FlightNumber");

                    b.HasKey("Id");

                    b.ToTable("AirlinesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
