// <auto-generated />
using System;
using ManageAirliness.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManageAirliness.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220525154404_initialmigration3")]
    partial class initialmigration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ManageAirliness.Model.Airlines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirlineAddress");

                    b.Property<int>("AirlineContactNumber");

                    b.Property<string>("AirlineName");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AirlinesDetails");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Airlines");
                });

            modelBuilder.Entity("ManageAirliness.Model.Inventory", b =>
                {
                    b.HasBaseType("ManageAirliness.Model.Airlines");

                    b.Property<DateTime?>("AirlineEndDate");

                    b.Property<double>("AirlinePrice");

                    b.Property<DateTime?>("AirlineStartDate");

                    b.Property<double>("AirlineTotalCost");

                    b.Property<int>("FlightNumber");

                    b.Property<string>("FromPlace");

                    b.Property<string>("InstrumentUsed");

                    b.Property<string>("Meal");

                    b.Property<int>("NoOfRows");

                    b.Property<string>("ToPlace");

                    b.Property<int>("TotalBusinessClassSeats");

                    b.Property<int>("TotalNonBusinessClassSeats");

                    b.ToTable("Inventory");

                    b.HasDiscriminator().HasValue("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
